version: '2'

services:
  db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=$AGR_POSTGRES_PASSWORD
      - POSTGRES_USER=$AGR_POSTGRES_USER
      - POSTGRES_DB=$AGR_POSTGRES_DB
  redis:
    image: redis
  web:
    build:
      context: ./frontend
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/16AGR/frontend:rw
      - ./schema:/16AGR/schema:rw
    links:
      - back
  back:
    build:
      context: ./backend
    expose:
      - "8080"
    ports:
      - "8081:8080"
    volumes:
      - ./backend:/16AGR/backend:rw
      - ./schema:/16AGR/schema:rw
    links:
      - db
      - redis
    environment:
      - POSTGRES_PASSWORD=$AGR_POSTGRES_PASSWORD
      - POSTGRES_USER=$AGR_POSTGRES_USER
      - POSTGRES_DB=$AGR_POSTGRES_DB
      - SESSION_SECRET=$AGR_SESSION_SECRET
