    version: '2'

    services:
      web:
        build:
          context: ./frontend
          #command: [bundle, exec, thin, -p, 3000]
        ports:
          - "80:8080"
        volumes:
          - ./frontend:/16AGR/frontend:rw
        links:
          - back:back
      back:
        build:
          context: ./backend
          #command: [bundle, exec, thin, -p, 3000]
        expose:
          - "8080"
        ports:
          - "8081:8080"
        volumes:
          - ./backend:/16AGR/backend:rw
